### ISSUE TITLE
Forum Reaction Bar flickering

### ISSUE THREAD

**Issue by nathanoy** [DaBluLite/Cyan#1]
The `React to post` message inside a forum thread is flickering very hard, when it reaches the top.
I am not sure if something with my setup is wrong, but it does not occur without the theme.

*see attached video*

https://user-images.githubusercontent.com/89805394/191368719-efad8953-ab41-47ab-b67a-52b4df9f91c5.mp4

**Comment by DaBluLite** [comment]
Fixed in commit [09b559c](https://github.com/DaBluLite/Cyan/commit/09b559cbbe4e4b5f55ed96c26a3ad0d132513e90)

**Comment by nathanoy** [comment]
wow, thank you!
Looks amazing now!
