### ISSUE TITLE
transparency module not working for vencord

### ISSUE THREAD

**Issue by yuma-dev** [DaBluLite/Cyan#10]
transparency is enabled and mica for everyone is running, other transparent themes are working.
tried importing it both in my QuickCSS and the online Themes
this is what it looks like:
![image](https://github.com/DaBluLite/Cyan/assets/76885566/7150a241-0712-4c75-94a2-226a68d353d9)

**Comment by DaBluLite** [comment]
sorry for the late response, will push a fix in a few minutes
