### ISSUE TITLE
Emoji picker off screen

### ISSUE THREAD

**Issue by nathanoy** [DaBluLite/Cyan#2]
The emoji picker is mostly off screen when opened by any of the shown (video attachment) buttons.

https://user-images.githubusercontent.com/89805394/192100282-b262044f-0a67-49c6-bac2-bc7d3ecfce40.mp4

**Comment by DaBluLite** [comment]
Fixed in [This commit](https://github.com/DaBluLite/Cyan/commit/a6a29f9bb0685c32aed3449d82292cd6044803bf)

**Comment by nathanoy** [comment]
are such reports welcome?
I would only continue if that is the case.

**Comment by DaBluLite** [comment]
Yes, if you experience any visual glitches with Cyan, please let me know so that I can fix them
