### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by waf1e** [DaBluLite/Cyan#3]
If you have GameActivityToggle, it pushes the setting icon off of the container

The audit log screen has no custom background

![image](https://user-images.githubusercontent.com/79756278/196830962-2972b770-e9b9-47c5-9957-c0c21a1f7233.png)
user pop out clicking the three dots

**Comment by DaBluLite** [comment]
[Fixed audit log custom background](https://github.com/DaBluLite/Cyan/commit/4e5bfb651b1ab611872e08a0ce9f520c65469b59), working on the rest

**Comment by DaBluLite** [comment]
> user pop out clicking the three dots

Can you explain in further detail?

**Comment by DaBluLite** [comment]
[Fixed user area buttons going out of bounds](https://github.com/DaBluLite/Cyan/commit/6fbbc3fb188e77e8ce130f5d83903403c426e6d2)

**Comment by waf1e** [comment]
> > user pop out clicking the three dots
> 
> Can you explain in further detail?

the line goes into the popout

**Comment by DaBluLite** [comment]
Yes, that's because the popout is meant to be see-through, but there is also a blur value in the theme that you can change to make most transparent backgrounds blurred
