### ISSUE TITLE
Impossible to turn off on accounts with long usernames.

### ISSUE THREAD

**Issue by ZmaZes** [DaBluLite/Cyan#4]
If you are using an account with a long username, the settings and deafen buttons will spill off of the edge of the column making it impossible to access settings in certain cases. You can see the issue in the image below.
I really like the UI and design of this theme, so I would love to see a fix for this so I can finally enjoy it.
![Uh-Oh](https://user-images.githubusercontent.com/116696525/197919038-65b921e0-bff3-4088-9779-9a5e5c5459c8.png)

**Comment by ZmaZes** [comment]
Update:
It seems to have fixed itself, I'm not sure how but if it breaks again I'll make another post.

**Comment by DaBluLite** [comment]
I will probably make the username part hoverable so that when you hover over it, it shows the name and tag while hiding the buttons. Also if this happens again, please use `CTRL + ,` to open settings.
