### ISSUE TITLE
Cannot scroll through channel list

### ISSUE THREAD

**Issue by Adaliciously** [DaBluLite/Cyan#6]
Trying to scroll through the channel list causes it to reset and go back up. One thing of note, not sure if it's an issue - I am using openasar only, no clientside mods.

![Discord_iM7z12UpAP](https://github.com/DaBluLite/Cyan/assets/7670940/42e9a1dc-4022-46a7-a5dc-12b94ad7284b)

**Comment by Adaliciously** [comment]
Tried on BetterDiscord, same issue occuring there

**Comment by DaBluLite** [comment]
Will have to take a look at this, maybe tomorow

**Comment by Adaliciously** [comment]
From my testing it feels like it could be potentially connected to monitors refresh rate? It happens way less often on my 60hz monitor

**Comment by DaBluLite** [comment]
The main cause of this issue is lazyloading, and the only way that this issue could theoretically be fixed is if I removed any changes in the size of the channels.

**Comment by DaBluLite** [comment]
I'm closing this, due to the issue being out of my scope

**Comment by Adaliciously** [comment]
Alright, are there any fixes that I can do on my own?
